//
// Created by rudi on 02/11/21.
//

#ifndef SIMPLE_BUFFER_TESTS_TEST_SIMPLE_STRUCTURE_HPP_
#define SIMPLE_BUFFER_TESTS_TEST_SIMPLE_STRUCTURE_HPP_

#endif //SIMPLE_BUFFER_TESTS_TEST_SIMPLE_STRUCTURE_HPP_
